### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [argex18/le-searcher#1]
Hi,<br><br>url : https://github.com/argex18/le-searcher/blob/2edea9ad440d9f67e902c24f80076f0a4ab53184/credentials.txt <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by argex18** [comment]
Thanks for the report, probably during my last commit i forgot to remove it.

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
